name: Release new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Select the new version type'
        required: true
        type: choice
        options: 
        - patch
        - minor
        - major
jobs:
  create-new-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Check out source code
      uses: actions/checkout@v3

    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - run: npm ci

    - name: 'Bump version and create a new tag'
      uses: 'phips28/gh-action-bump-version@master'
      id: bump-version
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag-prefix: 'v'
        version-type: ${{ github.event.inputs.version }}
        commit-message: 'CI: Bump version to {{version}}'

    - name: Push changes along with new tag
      run: git push origin main --follow-tags

    - name: Create new Release
      run: gh release create ${{ steps.bump-version.outputs.newTag }} --generate-notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
